version: 2.1
jobs:
  vote:
    docker:
      - image: circleci/ruby:2.4.2-node-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          name: Dependencies
          command: |
            npm install
      - save_cache:
          paths:
            - /node_modules  # location depends on npm version
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: cat test.js | sed 's/{{PASSWORD}}/'"$SKRATTAR_PASSWORD/g" | sed 's/{{USERNAME}}/'"$SKRATTAR_USERNAME/g" > ./tests/skrattar.tests.js
      - run: cat test.js | sed 's/{{PASSWORD}}/'"$FORLORAR_PASSWORD/g" | sed 's/{{USERNAME}}/'"$FORLORAR_USERNAME/g" > ./tests/forlorar.tests.js
      - run: cat test.js | sed 's/{{PASSWORD}}/'"$REDRIOT_PASSWORD/g"  | sed 's/{{USERNAME}}/'"$REDRIOT_USERNAME/g" > ./tests/redriot.tests.js
      - run: ls
      - run: npm run test
workflows:
  version: 2
  vote_dalaran_wow:
    jobs:
      - vote