version: 2.1
jobs:
  vote:
    docker:
      - image: circleci/node:10.2.1-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          name: Dependencies
          command: |
            npm install
      - save_cache:
          paths:
            - /node_modules  # location depends on npm version
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: mkdir tests
      - run: cat test.js | sed 's/{{PASSWORD}}/'"$SKRATTAR_PASSWORD/g" | sed 's/{{USERNAME}}/'"$SKRATTAR_USERNAME/g" > ./tests/skrattar.tests.js
      - run: cat test.js | sed 's/{{PASSWORD}}/'"$FORLORAR_PASSWORD/g" | sed 's/{{USERNAME}}/'"$FORLORAR_USERNAME/g" > ./tests/forlorar.tests.js
      - run: cat test.js | sed 's/{{PASSWORD}}/'"$REDRIOT_PASSWORD/g"  | sed 's/{{USERNAME}}/'"$REDRIOT_USERNAME/g" > ./tests/redriot.tests.js
      - run: ls
      - run: chmod -R u+x .
      - run: npm run test
workflows:
  version: 2
  sunday:
    triggers:
      - schedule:
          cron: "0 0,13 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - vote
  monday:
    triggers:
      - schedule:
          cron: "0 2,15 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - vote
  thuesday:
    triggers:
      - schedule:
          cron: "0 4,17 * * 2"
          filters:
            branches:
              only:
                - master
    jobs:
      - vote
  wednesday:
    triggers:
      - schedule:
          cron: "0 6,19 * * 3"
          filters:
            branches:
              only:
                - master
    jobs:
      - vote
  thursday:
    triggers:
      - schedule:
          cron: "0 8,21 * * 4"
          filters:
            branches:
              only:
                - master
    jobs:
      - vote
  friday:
    triggers:
      - schedule:
          cron: "0 10,23 * * 5"
          filters:
            branches:
              only:
                - master
    jobs:
      - vote
  saturday:
    triggers:
      - schedule:
          cron: "30 11 * * 6"
          filters:
            branches:
              only:
                - master
    jobs:
      - vote