version: 2.1
jobs:
  vote:
    docker:
      - image: selenium/standalone-chrome:3.141.59
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          name: Dependencies
          command: |
            sudo apt update
            sudo apt -y install nodejs npm
            npm install
      - save_cache:
          paths:
            - /node_modules  # location depends on npm version
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Vote
          command: |
            cat test.js      | sed 's/{{SKRATTAR_PASSWORD}}/'"$SKRATTAR_PASSWORD/g" | sed 's/{{SKRATTAR_USERNAME}}/'"$SKRATTAR_USERNAME/g" > test.exec.js
            cat test.exec.js | sed 's/{{FORLORAR_PASSWORD}}/'"$FORLORAR_PASSWORD/g" | sed 's/{{FORLORAR_USERNAME}}/'"$FORLORAR_USERNAME/g" > test.exec.js
            cat test.exec.js | sed 's/{{REDRIOT_PASSWORD}}/'"$REDRIOT_PASSWORD/g"   | sed 's/{{REDRIOT_USERNAME}}/'"$REDRIOT_USERNAME/g"   > test.exec.js
            npm run test
workflows:
  version: 2
  vote_dalaran_wow:
    jobs:
      - vote