version: 2.1
jobs:
  vote:
    docker:
      - image: selenium/standalone-chrome:3.141.59
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt -y install nodejs npm
      - run: npm install
      - run:
          name: Vote
          command: |
            cat test.js      | sed 's/{{SKRATTAR_PASSWORD}}/'"$SKRATTAR_PASSWORD/g" | sed 's/{{SKRATTAR_USERNAME}}/'"$SKRATTAR_USERNAME/g" > test.exec.js
            cat test.exec.js | sed 's/{{FORLORAR_PASSWORD}}/'"$FORLORAR_PASSWORD/g" | sed 's/{{FORLORAR_USERNAME}}/'"$FORLORAR_USERNAME/g" > test.exec.js
            cat test.exec.js | sed 's/{{REDRIOT_PASSWORD}}/'"$REDRIOT_PASSWORD/g"   | sed 's/{{REDRIOT_USERNAME}}/'"$REDRIOT_USERNAME/g"   > test.exec.js
      - run: npm run test
workflows:
  version: 2
  vote_dalaran_wow:
    jobs:
      - vote